### ISSUE TITLE
Strange question: Are you allowed to call it Dixit?

### ISSUE THREAD

**Issue by meadsteve** [arvoelke/Dixit#8]

**Comment by arvoelke** [comment]
If I am asked to take it down due to trademark infringement then I will. That is ultimately the decision of the company (Libellud) and, from what I understand, such decisions are typically made on the basis of good will and whether this is perceived as a competitor. I am not distributing their art, nor am I making any money, and intend this as a fan piece in support of the original board game. There is [another version](https://github.com/jminuscula/dixit-online) that distributes their artwork and so I would guess that is a bigger concern. That said, I will make it clearer in the readme that this is the work of fans, etc.
